
server:
  port: 10001
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/?chararcterEncoding=urf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yd.taozi.pojo
